ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr
AVR_TOOLS_DIR = /usr

BOARD_TAG     = mega2560
ARDUINO_PORT  = /dev/ttyACM*

ARDUINO_LIBS = Ethernet Ethernet/utility SPI LiquidCrystal

include /usr/share/arduino/Arduino.mk
